### ISSUE TITLE
JVMDebugger window always EMPTY

### ISSUE THREAD

**Issue by BlackBird-BB** [iGio90/Dwarf#103]
I use Dwarf to debug Wechat in both wsa(x86_64 android13) and real phone(android 7). After I set breakpoints in some methods, The apk is stoped, and I get some Information about runtime. But JVM debugger window isempty. I tried both on Win and linux(wsl), got the same.
Oh, I launch the Dawrf with -ds, It seems Runtime info has been passed to the Dwarf, I guess.
By the way, I use the latest version of Dwarf on git.
![1](https://user-images.githubusercontent.com/71928408/229270361-e0d66a7d-0f81-4ab0-98ae-1caf3dfbb983.png)

**Comment by BlackBird-BB** [comment]
In a addition, When I trigger the breakpoint, It'll show up JVM debugger window. And I press F7 key, It'll execute. And Dwarf show these uninterruptedly:
![image](https://user-images.githubusercontent.com/71928408/229268851-29c2d23a-7e0d-4750-a86f-bb4703f8b1b5.png)

**Comment by BlackBird-BB** [comment]
I remove -ds argument, and I got this info:

![3](https://user-images.githubusercontent.com/71928408/229269999-e427789a-ccd5-4f72-b3e7-1ba2abfa44ef.png)

I think this error is from the dex dynamically loading. I met the same error when I used the pure frida. But I could find this class in Java classes window, and that's excatly how i set breakpoints.

**Comment by iGio90** [comment]
If the dex is loaded during runtime, first thing first make sure it has been loaded. Once loaded, if you still can't find it, you have to iterate the class loaders. Frida recently updated those api. Check Java api in Frida docs, there is one which allows you to iterate on classloaders. With a classloader handle you can enumerate java loaded class. When you find the class matching yours, set that classloader as default and you can hook there

**Comment by BlackBird-BB** [comment]
Well, It's excatly what I did.I uesd to find the class loader like this:
```   javascript
var MyClass = "com.tencent.mm.sdk.storage.MAutoStorage"
function hooker() {
    let MAutoStorage = Java.use("com.tencent.mm.sdk.storage.MAutoStorage");
    MAutoStorage["getCreateSQLs"].implementation = function (mAutoDBInfo, str) {
        console.log(`MAutoStorage.getCreateSQLs is called: mAutoDBInfo=${mAutoDBInfo}, str=${str}`);
        let result = this["getCreateSQLs"](mAutoDBInfo, str);
        console.log(`MAutoStorage.getCreateSQLs result=${result}`);
        return result;
    };
}

function hook_dyn_dex() {
    Java.perform(function () {
        Java.enumerateClassLoaders({
            onMatch: function (loader) {
                try {
                    if (loader.findClass(MyClass)) {
                        Java.classFactory.loader = loader;
                        console.log(loader);
                    }
                } catch (error) {

                }
            }, onComplete: function () {
            }
        });
        hooker();
    })
}

hook_dyn_dex();
```
But how I let Dwarf to use this dex and show up some infomation in the JVMDebuggger window？

**Comment by PinkiePieStyle** [comment]
Was flying over the code and it's an bug. Normally you clicked an entry in the context panel and it populated the explorerview but there is no clickhandler or implementation to set new handle for the jvmexplorer.

The jvmexplorer should be exposed in api
https://github.com/iGio90/DwarfCore/blob/master/src/DwarfApi.ts#L1267
https://github.com/iGio90/DwarfCore/blob/master/src/logic_java.ts#L262
so you should be able to call it in your script and explore until fixed.

**Comment by iGio90** [comment]
WTF he is alive!

**Comment by BlackBird-BB** [comment]
hhhhhhhhhh, I report! iGio99 just said you' dead.
