### ISSUE TITLE
fail to delete hook

### ISSUE THREAD

**Issue by chensem** [iGio90/Dwarf#11]
![image](https://user-images.githubusercontent.com/27469499/51439215-e4a18f00-1cf1-11e9-9d0b-60c667497f72.png)
i want to delete the last hook. but it failed

**Comment by iGio90** [comment]
it's a typo! gonna fix in next commit. Quick fix for you ->
edit line 126 of lib/script.js.
replace it with:
`delete getDwarf().onLoads[hook.module];`
