### ISSUE TITLE
Dwarf crash when click Java classes

### ISSUE THREAD

**Issue by jhftss** [iGio90/Dwarf#12]
https://github.com/iGio90/Dwarf/blob/4e5154fdcf43430f5adc3c950787a360d1f0b4cc/ui/panel_java_methods.py#L19

**Comment by jhftss** [comment]
from lib.core import Dwarf

**Comment by iGio90** [comment]
thanks dude! 
https://github.com/iGio90/Dwarf/commit/268040006f5403081dbe1c3396fd387cd57bee7f
