### ISSUE TITLE
Not Able to launch 

### ISSUE THREAD

**Issue by mohittyagi11** [iGio90/Dwarf#13]
PS D:\Tools for Testing\Dwarf\Dwarf> python .\dwarf.py
adb: True
dev/emu: True
su: True
root: False

at least 3x True required
Traceback (most recent call last):
  File ".\dwarf.py", line 41, in <module>
    app_window = AppWindow(args)
  File "D:\Tools for Testing\Dwarf\Dwarf\ui\app.py", line 36, in __init__
    self.dwarf = Dwarf(self)
  File "D:\Tools for Testing\Dwarf\Dwarf\lib\core.py", line 80, in __init__
    self.script_manager = ScriptsManager(self)
  File "D:\Tools for Testing\Dwarf\Dwarf\lib\scripts_manager.py", line 24, in __init__
    self.update_scripts()
  File "D:\Tools for Testing\Dwarf\Dwarf\lib\scripts_manager.py", line 27, in update_scripts
    scripts = self.dwarf.get_git().get_dwarf_scripts()\
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by iGio90** [comment]
Checking in 5 minutes :) thanks!

**Comment by iGio90** [comment]
ok.. i've added a null check here https://github.com/iGio90/Dwarf/commit/724c907ef2b733c61a567adeb295d93250d3a300 that should at least fix the crash but you will face some more i think. Make sure ``git`` binary is in your PATH

**Comment by mohittyagi11** [comment]
Still:

adb: True
dev/emu: True
su: True
root: False

at least 3x True required
Traceback (most recent call last):
  File "D:\Tools for Testing\Dwarf\Dwarf\ui\ui_welcome.py", line 67, in run
    self.on_finished.emit('Failed to fetch commit list. Try later.')
TypeError: DwarfCommitsThread.on_finished[] signal has 0 argument(s) but 1 provided

**Comment by iGio90** [comment]
@PinkiePieStyle help here :D

**Comment by iGio90** [comment]
i guess
```
    on_finished = pyqtSignal()
```

should be

```
    on_finished = pyqtSignal(str)
```

**Comment by PinkiePieStyle** [comment]
There is nothing connected.
Comment out Line 61, 67, 90

**Comment by iGio90** [comment]
I'll commit @PinkiePieStyle way

**Comment by iGio90** [comment]
I'm closing this with https://github.com/iGio90/Dwarf/commit/c89094b442a2a76c54b127ad5632c84a09ed1255

thanks for report :)
