### ISSUE TITLE
Got some javascript errors

### ISSUE THREAD

**Issue by nikswap** [iGio90/Dwarf#16]
When choosing to start app will the terminal give this message:
unable to find method 'api'

And in the terminal is this message:
payload: {'type': 'error', 'description': 'ReferenceError: _log is not defined', 'stack': 'ReferenceError: _log is not defined\n    at /script1.js:38:6', 'fileName': '/script1.js', 'lineNumber': 38, 'columnNumber': 6}

Frida version 12.5.0

Rooted phone with magisk 19.1

**Comment by PinkiePieStyle** [comment]
fixed with
https://github.com/iGio90/Dwarf/commit/fcf78bc9fa5b2d9d29832e3941b00b2e68e7bae2#diff-f265d6a6b6b64d4d096fddcf7d620a76
