### ISSUE TITLE
Application crash on adding a watcher

### ISSUE THREAD

**Issue by lex0tanl** [iGio90/Dwarf#17]
Steps to reproduce: 

- injecting into application process

- adding hook on `android.api.Activity.onCreate`

- add watcher: `api.findExport('open')`

we get a crash:

`payload: {'type': 'error', 'description': 'ReferenceError: _this is not defined', 'stack': 'ReferenceError: _this is not defined\n    at new MemoryWatcher (/script1.js:1982:11)\n    at Object.DwarfApi.addWatcher (/script1.js:530:46)\n    at Dwarf._onHook (/script1.js:274:62)\n    at klass.<anonymous> (/script1.js:1890:28)\n    at f (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:2105:1), <anonymous>:1:272)', 'fileName': '/script1.js', 'lineNumber': 1982, 'columnNumber': 11}`

**Device info**
Model: GT-I9505
Arch/Rom:
> jfltexx:/ # uname -a
Linux localhost 3.4.112-Lineage-gd51a0c0 #1 SMP PREEMPT Fri Jan 20 20:25:34 EET 2017 armv7l

**Comment by iGio90** [comment]
I just fixed this with the last commit. Can you update and confirm it's working now? ^^

**Comment by lex0tanl** [comment]
can confirm it works :)

![Screenshot 2019-05-09 at 15 31 39](https://user-images.githubusercontent.com/1131891/57461812-98159b80-726f-11e9-9361-fd56a59f6d4d.png)

thanks a lot.
