### ISSUE TITLE
stable release

### ISSUE THREAD

**Issue by blshkv** [iGio90/Dwarf#18]
Could you please start cutting releases at some point so that the tool can be ported to Linux distros properly?

I would like to port it on Pentoo Linux. Thank you

**Comment by iGio90** [comment]
Hello! Yeah, we did a big refactor (UI and logic) and we are still fixing small things here and there. You are the 4th/5th asking this so i guess it will happens soon.

What do you mean by "port"? Whats not working there?

**Comment by blshkv** [comment]
Hey, thank you for the quick reply, happy that it will be a progress here.

By port I mean that we will be writing an ebuild (script) so that our users can install it system-wide with a standard command (emerge dwarf).

Cheers

**Comment by blshkv** [comment]
It wasn't done. Why did you close the report?

**Comment by PinkiePieStyle** [comment]
https://pypi.org/project/dwarf-debugger/

**Comment by blshkv** [comment]
Great, thank you

**Comment by blshkv** [comment]
This is a precompiled binary. Can you also tag and cut a source code here, at github for crazy people like me so that we can compile it?

**Comment by blshkv** [comment]
I was expecting a tar-ball here, in a release section. But I found it at pypi.
Thanks a lot!

**Comment by PinkiePieStyle** [comment]
with dwarf >= 2.0 there are releases here too
thats the last 1.0 wich is 'somewhat stable'
