### ISSUE TITLE
Allow choice of device when multiple devices are connected

### ISSUE THREAD

**Issue by Oreaz** [iGio90/Dwarf#19]
I do have multiple devices connected.

Would it be possible to add a dropdown to let me choose which I want to use.
A argument on dwarf.py would be nice also.

![image](https://user-images.githubusercontent.com/16743608/57988767-3389e600-7a92-11e9-9554-993f57b7bae0.png)

**Comment by PinkiePieStyle** [comment]
![devwindow](https://user-images.githubusercontent.com/7350146/58332689-0e9fc500-7e3c-11e9-9d79-a08b9c43cdc9.png)

**Comment by iGio90** [comment]
That guy <3
