### ISSUE TITLE
IOS not supported ???

### ISSUE THREAD

**Issue by folkene** [iGio90/Dwarf#20]
Hello,

It's me, again :). I'm trying to use DWARF with my iphone, and... I cannot even click on the apple button. If I press the Android Button, I can see a green ruban saying "Iphone Connected" but the tools does not give me any options.

Thanks a lot,
 - Wally

**Comment by iGio90** [comment]
Heyhey! Yes iOS is totally missing but very easy to-do. We lack of an iOS device to make it so we are waiting some good soul. lib/android_session.py is what needs to be ported and linked to app

**Comment by folkene** [comment]
Ok thanks for the very quick reply :)

**Comment by iGio90** [comment]
Its very easy to do, we just can't test if it works otherwise we had it already done. Eventually someone which will care about iOS can add extra features as I'm doing for Android. If you are going to do it feel free to ping me for core logic/arm/Frida stuff or @PinkiePieStyle for UI/x86

**Comment by PinkiePieStyle** [comment]
You can try the test branch ive created. Press Remote Session and try attaching to something.
I have not tested something only copied localsession but allows usb device
There is no Spawnslist too

**Comment by iGio90** [comment]
this is misleading. Just name it iOS session and attach to the ios button, then someone will do the job?

**Comment by PinkiePieStyle** [comment]
Why? Its an remote session too?
No IOS related stuff in there why creating the lib for it.
Someone can copy remote_session.py and create ios_session.py with ios related things in it.

**Comment by iGio90** [comment]
yeah but i mean... just prepare for him/whoever a file called ios-session linked to the button which just need the necessary edits. Feel free to leave remote one as well linked to the other button. What i'm saying is just get the ui stuffs ready so some iOS can just click the button and test the core logic

**Comment by folkene** [comment]
I got some spare time right now. I'm gonna try implementing something :).

I let you know about my progress

**Comment by iGio90** [comment]
nice! ping me on slack for any info or point-to-code!
