### ISSUE TITLE
Failed to spawn or attach to processes

### ISSUE THREAD

**Issue by matbrik** [iGio90/Dwarf#23]
Hi, after this  #22  I tried to spawn an application i get a pop up error with Failed spawning "com.package", in the details dwarf says 'runtime' is an invalid keyword argument for this function

I checked where the error could come from and it could be inside load_script() in lib/core.py
I get the same error if I try to attach to a process es Failed attaching to [10653, 'com.whatsapp']

**Comment by PinkiePieStyle** [comment]
sorry but cant reproduce
Whatsapp 2.19.149 works fine here in emu
![whatsapp](https://user-images.githubusercontent.com/7350146/58480076-d65cf700-8159-11e9-8bef-48ca12584b6d.png)

**Comment by GSharma789** [comment]
for me process tab showing all running process but spawn tab is empty ( only shown when first time i start frida from dwarf then even after restarting frida or dwarf only process tab are filled ) . OS : windows 7 x86 , FRIDA: 12.6.0 , EMULATOR: blustack 4.4 and nox playes 5.0

**Comment by PinkiePieStyle** [comment]
in most cases when spawns are missing its frida timeouterror
im using nox 6.2.7.x here for testing and it shows always spawns with frida >12.5.2
