### ISSUE TITLE
su: invalid uid/gid

### ISSUE THREAD

**Issue by Goldtulip** [iGio90/Dwarf#25]
when I use Dwarf on version 12.6.1, I find an error on mount_system():**su: invalid uid/gid**   fix it by use:do_adb_command('shell su 0 mount -o rw,remount /'). shell su -c not work well.  it happens also on the funcion:check_requirements

**Comment by iGio90** [comment]
can you find a rule to pr the if/else for -c/0?
i think something like su --version maybe? or something like that

**Comment by Goldtulip** [comment]
I only find [this](https://stackoverflow.com/questions/37525977/android-run-script-in-adb-shell), It seems need use "su 0" in any instances.

**Comment by iGio90** [comment]
Yeah ofc... If one nerds 0 all others would needs as well

**Comment by PinkiePieStyle** [comment]
should be fixed with https://github.com/iGio90/Dwarf/commit/cdce0e7c8fdf896661ba162704163b56be0a799f
