### ISSUE TITLE
Check missing

### ISSUE THREAD

**Issue by Reversive** [iGio90/Dwarf#27]
https://github.com/iGio90/Dwarf/blob/7f59584b33107d75a4ba233217b0469d41a8598c/ui/widgets/list_view.py#L233

it's not checking if the input is empty (leaving the textbox blank when searching in any list) hence crashing the app.

Error log=> 
```
have_result, search_results = self.contains_text(input, stop_at_match=False)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by PinkiePieStyle** [comment]
thx 
https://github.com/iGio90/Dwarf/commit/cc2775aaa0580b895ebe73777aa90d72db698997
