### ISSUE TITLE
Frida binary cli option suggestion

### ISSUE THREAD

**Issue by gorelics** [iGio90/Dwarf#29]
Hi, thanks for the cool software. It will be nice to add some cli option to specify frida server binary name. I'm using MagiskFrida add-on, it installs frida binary as frida-server to /system/xbin. It's not to hard to modify Dwarf sources or MagiskFrida package but anyway such option will be useful. Or just create const in one file that will be used everywhere.

**Comment by PinkiePieStyle** [comment]
https://github.com/iGio90/Dwarf/commit/15ffa106aa52cc28d9643b26071ff6be6b2dd2ba
