### ISSUE TITLE
pidof parsing problem

### ISSUE THREAD

**Issue by gorelics** [iGio90/Dwarf#30]
On my android 6.0 device pidof returns all processes ids and always "Start frida" button appears
```bash
shell@my70ds:/ # pidof frida
1 2 3 5 6 7 8 9 10 11 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 41 ...
76 277 278 279 282 283 286 289 290 291 293 294 295 296 297 299 302 305 306 309 312 313 398 408 40
```

Maybe not return here but try other options 
https://github.com/iGio90/Dwarf/blob/master/lib/adb.py#L322

**Comment by PinkiePieStyle** [comment]
whats the result of
su -c pidof -s 'frida'
su -c pidof -s 'frida-sever'

**Comment by gorelics** [comment]
prints 1 init process id

**Comment by iGio90** [comment]
Can i have more info? Device, ROM, and pidof --version or something to identify the binary?

**Comment by gorelics** [comment]
model:LG_H422 device:my70ds
release 6.0
[ro.bootimage.build.date]: [Thu Jul 14 09:25:07 KST 2016]
[ro.bootimage.build.date.utc]: [1468455907]
[ro.build.characteristics]: [default]
[ro.build.date]: [Thu Jul 14 09:21:37 KST 2016]
[ro.build.date.utc]: [1468455697]
[ro.build.default_country]: [CIS]
[ro.build.description]: [my70ds_global_com-user 6.0 MRA58K 1619609164c2c
[ro.build.display.id]: [MRA58K]
[ro.build.factory_country]: [CIS]
[ro.build.factory_operator]: [OPEN]
[ro.build.fingerprint]: [lge/my70ds_global_com/my70ds:6.0/MRA58K/1619609164c2
[ro.build.flavor]: [my70ds_global_com-user]
[ro.build.host]: [LGEACI8R5]
[ro.build.id]: [MRA58K]
[ro.build.product]: [my70ds]
[ro.build.sbp]: [1]
[ro.build.sbp.version]: [20]
[ro.build.tags]: [release-keys]
[ro.build.target_country]: [CIS]
[ro.build.target_operator]: [OPEN]
[ro.build.target_region]: [CIS]
[ro.build.type]: [user]
[ro.build.user]: [jenkins]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [1619609164c2c]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [6.0]
[ro.build.version.sdk]: [23]
[ro.build.version.security_patch]: [2016-07-01]
[ro.lge.build.basetag]: [LAMPMR160404]
[ro.lge.build.branch]: [mt6582_m_y70_global_com_mp_160517]
[ro.build.product]: [my70ds]
[ro.product.board]: [mt6582]
[ro.product.brand]: [lge]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.device]: [my70ds]
[ro.product.locale]: [ko-KR]
[ro.product.locale.language]: [en]
[ro.product.locale.region]: [GB]
[ro.product.manufacturer]: [LGE]
[ro.product.model]: [LG-H422]
[ro.product.name]: [my70ds_global_com]

**Comment by gorelics** [comment]
I have another more serious problem, but it related to frida server https://github.com/frida/frida-java/issues/115

**Comment by gorelics** [comment]
This problem was fixed in the new update, thanks
