### ISSUE TITLE
Quick filter feature

### ISSUE THREAD

**Issue by gorelics** [iGio90/Dwarf#31]
It will be useful to quick filter the lists (processes, classes, exports) like in IDA 

![IDA Quick Filter](https://i106.fastpic.ru/big/2019/0611/14/e8f2bc9c175a1252942fd96adda55e14.jpg)

**Comment by iGio90** [comment]
Did you tried to ctrl+f on any lista? :'D

**Comment by gorelics** [comment]
Really! ))) Thanks! No info about that, maybe need to add item search to the context menu

**Comment by iGio90** [comment]
+1 for the quick right-click shortcut. I love shortcuts :D leaving this open so we got a remind to add it :)
