### ISSUE TITLE
[Feature Request] "Copy value" context menu support for sidebar pane lists

### ISSUE THREAD

**Issue by Pilfer** [iGio90/Dwarf#34]
Specifically in the "Context" and "Backtrace" pane.

**Comment by PinkiePieStyle** [comment]
https://github.com/iGio90/Dwarf/commit/11dfcbbdd53c3ed5f9b21864311d2841bc31824c

**Comment by Pilfer** [comment]
Thanks @PinkiePieStyle  <3
