### ISSUE TITLE
Dwarf on non-rooted Android device and memory search

### ISSUE THREAD

**Issue by VRMegaFan** [iGio90/Dwarf#39]
Hello,
first of all - HUGE THANKS for your AWESOME tool on top of Frida! It helps immensely!
I have two issues/questions about it right now:
1) I had to change device_window.py in order to make it recognize frida-gadget for non-rooted Android device:

> self.title = 'Android Session'
> self.device = frida.get_usb_device()

(instead of None)
In this case the process with injected Frida is being shown and everything seems to work just fine.
2) I couldn't find the functionality for memory search, e.g. searching for certain bytes in memory. Do you intend to add this functionality as well?
Again - many thanks for your work and good luck!!!

**Comment by PinkiePieStyle** [comment]
for 2)
CTRL+F3 or View->Subview->Search

**Comment by PinkiePieStyle** [comment]
for 1) pls try latest master
https://github.com/iGio90/Dwarf/commit/92984d6c3abbbabe1373ec72f3108729f3c5ae70

**Comment by VRMegaFan** [comment]
> for 1) pls try latest master
> [92984d6](https://github.com/iGio90/Dwarf/commit/92984d6c3abbbabe1373ec72f3108729f3c5ae70)

Strangely now I can't get rid of the message "A newer Version of Dwarf is available. Checkout Dwarf on GitHub for more informations" - even after clicking on "Update now" I see the same message again and again.

**Comment by PinkiePieStyle** [comment]
delete .git_cache folder
