### ISSUE TITLE
Dumping from module panel

### ISSUE THREAD

**Issue by Reversive** [iGio90/Dwarf#49]
If I go into the module panel and try to dump a module (selecting any .so using right click>dump binary) dwarf crashes (tested with several apps).

Crash report:
![Kz4KKUe](https://user-images.githubusercontent.com/14043761/63812131-cba03280-c8ff-11e9-8a91-670a4d2e7922.png)

**Comment by iGio90** [comment]
Thanks <3

https://github.com/iGio90/Dwarf/commit/9682294ad446454f0c569ec9514ca009a8bcfd19
