### ISSUE TITLE
Not working on iOS 12.2 nor 11.2.5 ?

### ISSUE THREAD

**Issue by kevinpiac** [iGio90/Dwarf#52]
Hey guys,

First, thank you for this amazing tool it looks very very promising with a very clean interface!

I'm able to spawn/attach a process running on my iPhone, however, I can not see anything related to the memory nor setting breakpoint nor playing around with classes/methods.

I've tried with :
- iPhone 6 running on iOS 11.2.5
- iPhone 6 plus running on iOS 12.2
- Tried with different apps such as Snapchat, Phone, ... same result 

Here's my screen, you can also see that an error message appears in the console when I try to set a breakpoint to a method. 

<img width="539" alt="Capture d’écran 2019-10-04 à 22 28 23" src="https://user-images.githubusercontent.com/15961122/66238355-bb962280-e6f7-11e9-8626-6442e0608b3d.png">
<img width="2558" alt="Capture d’écran 2019-10-04 à 22 28 39" src="https://user-images.githubusercontent.com/15961122/66238356-bb962280-e6f7-11e9-985f-768585d5b4f6.png">
<img width="2560" alt="Capture d’écran 2019-10-04 à 22 28 32" src="https://user-images.githubusercontent.com/15961122/66238357-bb962280-e6f7-11e9-843c-8c06c0d8cf20.png">

**Comment by PinkiePieStyle** [comment]
https://github.com/iGio90/Dwarf/commit/54e654f90f8607c54a6eebab5c4939dfac8674b9
