### ISSUE TITLE
Reboot loop on device identification

### ISSUE THREAD

**Issue by Reversive** [iGio90/Dwarf#55]
Hey, i am trying to run dwarf on a samsung galaxy s7 (G930FD, a.ver 8.0) but each time the debugger identifies the device the phone reboots (that is, i open a new session and as soon as my phone is detected and added to the device list, it restarts my phone), i used dwarf with the same phone some months ago and was working fine, all the checks are passed (root/adb/device/etc). Tried on two different computers and the result was the same.

**Comment by PinkiePieStyle** [comment]
local frida and remote on device on latest version 12.8.1?

**Comment by Reversive** [comment]
My frida server was outdated, thanks.
