### ISSUE TITLE
Error on any js api command execution

### ISSUE THREAD

**Issue by Tolsi** [iGio90/Dwarf#57]
After every command in javascript console, I see an error on the right text area: 

```21:22:59.800784  TypeError: Cannot read property 'apply' of undefined at Object.api (src/index.ts:81:33) at handleRpcMessage (frida/runtime/message-dispatcher.js:49:1) at handleMessage (frida/runtime/message-dispatcher.js:29:1)```

or 

```21:33:39.321790  TypeError: Cannot read property 'then' of null at handleRpcMessage (frida/runtime/message-dispatcher.js:50:1) at handleMessage (frida/runtime/message-dispatcher.js:29:1)```

**Comment by PinkiePieStyle** [comment]
javascript console is for javascript code
so dont know what your 'every command' means

**Comment by PinkiePieStyle** [comment]
putBreakpoint(findExport('open'));
http://www.giovanni-rocca.com/dwarf/tutorials/
