### ISSUE TITLE
UI resets after process restart

### ISSUE THREAD

**Issue by Tolsi** [iGio90/Dwarf#58]
I want to install hooks and catch them after restarting the process. I set them in 'breakpoint' area, then I restart the process (Process - Restart), it looks like the interface is being recreated and I lose all my hooks. Is it ok?

**Comment by PinkiePieStyle** [comment]
yeah, thats how it works in current dwarf

**Comment by Tolsi** [comment]
but maybe it would be more convenient to do this optionally? It seems to me that saving previous breakpoints is convenient

**Comment by PinkiePieStyle** [comment]
the bpaddress is the memoryaddress and with aslr you cant ensure that old address is new address.
it was in before https://github.com/iGio90/Dwarf/commit/9b213c611ced5ecc2185ec2632170cd478760868
but wasnt perfect so it is removed in actual code.

with next version stored breakpoints are back but not all breakpoints and its not bulletproof
