### ISSUE TITLE
Watchpoints

### ISSUE THREAD

**Issue by Reversive** [iGio90/Dwarf#59]
I'm having trouble setting watchpoints for a specific address (regardless if it's r/w/e), i'm trying to set them as 0xAddress (i.e 0x9EB27370) but it's throwing the following error:
![image](https://user-images.githubusercontent.com/14043761/75086373-1fd44a00-5512-11ea-828d-592d496ef14c.png)

**Comment by PinkiePieStyle** [comment]
Flags missing

```
/**
     * Put a watchpoint on the given address
     *
     * ```javascript
     * putWatchpoint(0x1000, 'r');
     *
     * var target = findExport('memcpy');
     * Interceptor.attach(target, {
     *     onLeave: function(ret) {
     *         putWatchpoint(this.context.x0, 'rw', function() {
     *            log(backtrace(this.context));
     *         });
     *     }
     * });
     * ```
     * @param address
     * @param flags
     * @param callback
     */
```

**Comment by PinkiePieStyle** [comment]
https://github.com/iGio90/Dwarf/commit/6d5c25cc63281b9d2799dcbc01d1be8ea78bb137
