### ISSUE TITLE
"tabBar" ui is NoneType

### ISSUE THREAD

**Issue by sieunhando** [iGio90/Dwarf#6]
I'm using Windows 10x64, and have this error
```
  File "xxxxx\Dwarf\ui\ui_session.py", line 101, in __init__
    self.tabBar().tabButton(0, QTabBar.LeftSide).resize(0, 0)

AttributeError: 'NoneType' object has no attribute 'resize'
```
It work fine if comment that line.

**Comment by nmweizi** [comment]
me to

**Comment by iGio90** [comment]
Thanks! Can you guys help me out fixing this? Seems and issue in win only actually

**Comment by iGio90** [comment]
Yeah but you can "close" the session tab this way. That line is hiding the "X" for close the tab.

**Comment by sieunhando** [comment]
> Yeah but you can "close" the session tab this way. That line is hiding the "X" for close the tab.

http://prntscr.com/m3adkf
It still show bro :D

**Comment by iGio90** [comment]
yeah! and that line you commented is supposed to hide it (actually it's doing the job on linux and osx) can we move this to slack? link in readme!

**Comment by iGio90** [comment]
https://github.com/iGio90/Dwarf/commit/0146e7b5c45ac4264ff3479a4cf4623591fbda93
