### ISSUE TITLE
Where can i get Dwarf version 2 ???

### ISSUE THREAD

**Issue by Pr0214** [iGio90/Dwarf#61]
NetworkRequests.js told me  that "//Dwarf >= 2.0.0 required!",or it will occur error
![image](https://user-images.githubusercontent.com/44285766/75748660-f958af00-5d5a-11ea-92df-d1a72bceb8ad.png)
Where can i get Version 2.0

**Comment by PinkiePieStyle** [comment]
wait for it ;)

added versioncheck to scriptsmanager
