### ISSUE TITLE
trace don’t del

### ISSUE THREAD

**Issue by zhaoboy9692** [iGio90/Dwarf#63]
![image](https://user-images.githubusercontent.com/35800413/76069551-029d8200-5fce-11ea-8893-e0ac05414ea8.png)
I want to delete some, but I can't find a way

**Comment by PinkiePieStyle** [comment]
try doubleclicking an entry

**Comment by zhaoboy9692** [comment]
no del

**Comment by zhaoboy9692** [comment]
Cannot be deleted。。。。

**Comment by PinkiePieStyle** [comment]
tried with latest version???

tested it multiple times

doubleclick entry
