### ISSUE TITLE
can not be breaked when using putBreakpoint

### ISSUE THREAD

**Issue by dengtongtongtong** [iGio90/Dwarf#64]
when I start dwarf below, it can not break when the event fired. However, it can be break when I choose the same method from  the toolbox Java-> classes. 
> dwarf -t android com.example.king.testappsflyer -s debug.js
this is my jscode below.
![image](https://user-images.githubusercontent.com/7939201/76137301-22888080-6076-11ea-890a-f3ee97ec0da8.png)
dwarf 1.0.4 is used
![image](https://user-images.githubusercontent.com/7939201/76137342-c7a35900-6076-11ea-8664-1ebe1f8054ef.png)
BTW, thanks for your great work, really helps a lot

**Comment by dengtongtongtong** [comment]
In addition, I found when I start dwarf with '-bs' following below steps, it can not stopped at breakpoint
> start with '-bs -t android' option
> add some breakpoint
> resume hooked app
> interact hooked app to trigger the breakpoint

While it can stopped following these steps below
> start with '-bs -t android' option
> resume hooked app
> add some breakpoint
> interact hooked app to trigger the breakpoint

Can somebody give some advice

dwarf version:1.0.4
frida 12.8.14

**Comment by dengtongtongtong** [comment]
What I need is start with '-bs' option, add some breakpoint, resume the app, and watch these breaks

**Comment by PinkiePieStyle** [comment]
think your problem is that the class isnt loaded at initbp

can u try with

```
var targetClass = 'android.widget.ListView';

hookClassLoaderClassInitialization(targetClass, function() {
    putBreakpoint(targetClass + '.setAdapter', function(args) {
        console.log('bp');
    });
});
```

**Comment by dengtongtongtong** [comment]
thx, I think what you say make sense. But still it cannot break. And even the breakpoint winidow does not show it when I start dwarf with 
`dwarf -t android com.example.king.testappsflyer -s debug.js`
nothing on that window

![image](https://user-images.githubusercontent.com/7939201/76145761-88512880-60c7-11ea-8ddb-b848c9803976.png)

**Comment by PinkiePieStyle** [comment]
Ok thats something other, when it doesnt show in list there is nothing attached

start with additional -ds

**Comment by PinkiePieStyle** [comment]
when using the gitversion from dwarf 
change the core.py and move these 2 lines
https://github.com/iGio90/Dwarf/blob/master/dwarf_debugger/lib/core.py#L369

to line 361

**Comment by PinkiePieStyle** [comment]
Test with 1.0.5

**Comment by dengtongtongtong** [comment]
can not launch 1.05 with this error
`
AttributeError: 'AppWindow' object has no attribute 'welcome_window'
`

**Comment by PinkiePieStyle** [comment]
1.0.6
