### ISSUE TITLE
empty debug window

### ISSUE THREAD

**Issue by 0x410c** [iGio90/Dwarf#67]
i put a breakpoint on class constructor, breakpoint gets hit but everything is blank!!
```

02:35:04 [ERROR-LogicJava.hook] Error: java.lang.ClassNotFoundException: Didn't find class "com.whatsapp.jobqueue.job" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.whatsapp-LqLY5Xrpfu9W8PvMcn2vHg==/base.apk"],nativeLibraryDirectories=[/data/app/com.whatsapp-LqLY5Xrpfu9W8PvMcn2vHg==/lib/arm64, /data/app/com.whatsapp-LqLY5Xrpfu9W8PvMcn2vHg==/base.apk!/lib/arm64-v8a, /system/lib64]]
02:35:12 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
02:35:12 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
02:35:12 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
02:35:12 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
02:35:12 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
02:35:12 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
```

**Comment by PinkiePieStyle** [comment]
Please test with the git version

**Comment by 0x410c** [comment]
same just the string u changed in the code!

`14:42:06 [ERROR-jvmExplorer-2] TypeError: Cannot read property 'className' of undefined`

**Comment by 0x410c** [comment]
simple to reproduce load whatsapp apk latest, attach to it, put breakpoint on constructor `com.whatsapp.jobqueue.job.SendE2EMessageJob.<init>`

and bam nothing!

**Comment by PinkiePieStyle** [comment]
can u try this core.js
replace in [dwarf_dir]\dwarf_debugger\lib
[core.zip](https://github.com/iGio90/Dwarf/files/4365817/core.zip)

**Comment by 0x410c** [comment]
same 

```
12:12:20 [ERROR-LogicJava.hook] Error: java.lang.ClassNotFoundException: Didn't find class "com.whatsapp.jid" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.whatsapp-n5BMG6bSlJQyLNN34iuKXw==/base.apk"],nativeLibraryDirectories=[/data/app/com.whatsapp-n5BMG6bSlJQyLNN34iuKXw==/lib/x86_64, /data/app/com.whatsapp-n5BMG6bSlJQyLNN34iuKXw==/base.apk!/lib/x86_64, /system/lib64]]
12:13:26 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
12:13:26 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
12:13:26 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
12:13:26 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
12:13:26 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
12:13:26 [ERROR-jvmExplorer-2] TypeError: Cannot read property '$className' of undefined
```

**Comment by PinkiePieStyle** [comment]
any code to reproduce?

seems ur hooking "com.whatsapp.jid" wich doesnt exists

can see and hook "com.whatsapp.jid.Jid"

**Comment by 0x410c** [comment]
i am doing thins on x86_64 android 9 emulator,

also its still the same!
![image](https://user-images.githubusercontent.com/12459304/77258935-1f2af280-6c3b-11ea-8ab0-cb4c459a2f04.png)

notice the context menu first menu though, it shows some hexadecimal (maybe opcodes?), and it changes when cursor position changes,
so maybe data is there but its not able to display it?

**Comment by 0x410c** [comment]
also about reproduction no matter where i put breakpoint any method there is nothing i can see, its not with in something particular but more general!

**Comment by PinkiePieStyle** [comment]
> i am doing thins on x86_64 android 9 emulator,
> 
> also its still the same!
> ![image](https://user-images.githubusercontent.com/12459304/77258935-1f2af280-6c3b-11ea-8ab0-cb4c459a2f04.png)
> 
> notice the context menu first menu though, it shows some hexadecimal (maybe opcodes?), and it changes when cursor position changes,
> so maybe data is there but its not able to display it?

Its always empty for java stuff its native only
left side is hexview from memory and right is disam
it shows something when hooking native stuff

**Comment by 0x410c** [comment]
wheres the disassembly then?

**Comment by PinkiePieStyle** [comment]
for java u have context/jvmdebugger only in ui
hook the native part in the libs or u need to handle extra javastuff in ur script

**Comment by 0x410c** [comment]
no bytecode disassembly?
