### ISSUE TITLE
Can't find d2j-dex2jar.bat

### ISSUE THREAD

**Issue by nevinhappy** [iGio90/Dwarf#70]
This tool is cool , When I'm trying to use to decompile an APK file . It shows "failed to find d2j-dex2jar.bat". And I can't find and place to configure path for this tool. 
So is there a way to integrate this tool to Dwarf ?

**Comment by PinkiePieStyle** [comment]
get https://github.com/pxb1988/dex2jar/files/1867564/dex-tools-2.1-SNAPSHOT.zip
put files in C:\dex2jar\ or whatever
add (C:\dex2jar or whatever) to PATH var
