### ISSUE TITLE
Remounting /system fails because it's missing in /proc/mounts

### ISSUE THREAD

**Issue by sn0opy** [iGio90/Dwarf#71]
I am running OxygenOS 10.5.4 (OnePlus stock OS) with a Magisk patched bootloader. Dwarf provides a way to automatically install frida into /system. One of the steps is remounting /system to make it writeable which fails on my device.

```
# mount -o rw,remount /system
mount: '/system' not in /proc/mounts
```

```
# cat /proc/mounts | grep system
/sbin/.magisk/block/system_root /sbin/.magisk/mirror/system_root ext4 ro,seclabel,relatime,discard 0 0
/sbin/.magisk/block/system_root /sbin/wlchg ext4 ro,seclabel,relatime,discard 0 0
/sbin/.magisk/block/system_root /sbin/dashd ext4 ro,seclabel,relatime,discard 0 0
/dev/block/loop2 /system/reserve ext4 ro,context=u:object_r:system_file:s0,relatime 0 0
```

I know that Dwarf does have a check for `/system_root`, but it does not seem to work in my case, since it just sets the system partition's name to `/system_root` which doesn't even exist.

I'm happy to share any further logs if needed.

**Comment by PinkiePieStyle** [comment]
pls try
in adb.py line 197
```
if '/system_root' in res:
    self._syspart_name = '/system_root'
    if '/sbin/.magisk/mirror/system_root' in res:
        self._syspart_name = '/sbin/.magisk/mirror/system'
        #self._syspart_name = '/sbin/.magisk/mirror/system_root/system'
```
or uncomment the 'system_root/system'

**Comment by sn0opy** [comment]
I don't think this will help either, since this is still not my actual system partition I think.

```
# mount -o rw,remount /sbin/.magisk/mirror/system_root
'/sbin/.magisk/block/system_root' is read-only
```

**Comment by PinkiePieStyle** [comment]
su -c mount

think sysdir should be 
'/sbin/.magisk/mirror/system_root/system'

test with latest commit

**Comment by sn0opy** [comment]
There has sneaked in an extra `/` in line 201. I've updated it to 
```
if '/sbin/.magisk/block/system_root' in res:
```
to actually use the intended path. 

But as stated above, manually mounting said path does not work due to the message you see on the screen. See the "#" in front of the command. I was trying to point out I was doing this as root already ;)

**Comment by 4val0v** [comment]
Same problem when installing Frida from Dwarf
Nexus 6 - Android 5.0
_Console:_
```
failed to mount /system on device
```


[adb.py line 196](https://github.com/iGio90/Dwarf/blob/2a0abe413476d1e7ee4b91b32b6eef9e9aefa1a1/dwarf_debugger/lib/adb.py#L196)
``` python
res = self._do_adb_command('shell mount | grep system')
```
Return:
```
/dev/block/platform/msm_sdcc.1/by-name/system /system ext4 ro,seclabel,relatime,data=ordered 0 0
/sbin/.magisk/block/system /sbin/.magisk/mirror/system ext4 ro,seclabel,relatime,data=ordered 0 0
```
Next command: (not working)
```
shell su -c mount -o ro,remount /sbin/.magisk/mirror/system
```
`rm` / `mv` etc... - Read-only file system

**Comment by 4val0v** [comment]
This method works for me on Nexus 5X and Nexus 6
```shell
Notebook-home:~ paul$ adb shell
shell@shamu:/ $ su
root@shamu:/ # mount -o rw,remount /
root@shamu:/ # touch /system/xbin/texxxxx                                      
root@shamu:/ # ls -la /system/xbin/ | grep tex                                 
-rw-r--r-- root     root            0 2020-04-26 05:04 texxxxx
```

**Comment by PinkiePieStyle** [comment]
> Same problem when installing Frida from Dwarf
> Nexus 6 - Android 5.0
> _Console:_
> 
> ```
> failed to mount /system on device
> ```
> 
> [adb.py line 196](https://github.com/iGio90/Dwarf/blob/2a0abe413476d1e7ee4b91b32b6eef9e9aefa1a1/dwarf_debugger/lib/adb.py#L196)
> 
> ```python
> res = self._do_adb_command('shell mount | grep system')
> ```
> 
> Return:
> 
> ```
> /dev/block/platform/msm_sdcc.1/by-name/system /system ext4 ro,seclabel,relatime,data=ordered 0 0
> /sbin/.magisk/block/system /sbin/.magisk/mirror/system ext4 ro,seclabel,relatime,data=ordered 0 0
> ```
> 
> Next command: (not working)
> 
> ```
> shell su -c mount -o ro,remount /sbin/.magisk/mirror/system
> ```
> 
> `rm` / `mv` etc... - Read-only file system

mount -o ro,.. < readonly

working on a fallback

@sn0opy can u try the syspart_fallback branch
set frida path in adb.py line 48 self._frida_path = ''

adding some find / -name frida-server + path via prefs later
