### ISSUE TITLE
Misunderstanding with requirements (capstone)

### ISSUE THREAD

**Issue by 4val0v** [iGio90/Dwarf#74]
[Dwarf/dwarf_debugger/dwarf.py](https://github.com/iGio90/Dwarf/blob/2a0abe413476d1e7ee4b91b32b6eef9e9aefa1a1/dwarf_debugger/dwarf.py#L87) - line 87
```
 _check_package_version('capstone', '4.0.0')  # problem with 4.0.1 as installed 4.0.1 returns 4.0.0
```
[Dwarf/requirements.txt](https://github.com/iGio90/Dwarf/blob/2a0abe413476d1e7ee4b91b32b6eef9e9aefa1a1/requirements.txt#L1)
```
capstone>=4.0.1
```

**Comment by PinkiePieStyle** [comment]
it's to prevent install loop

current capstone 4.0.1 pypi package returns 4.0.0
CS_API_MAJOR = 4
CS_API_MINOR = 0
CS_VERSION_EXTRA = 0
