### ISSUE TITLE
Empty spawn and procs

### ISSUE THREAD

**Issue by 4val0v** [iGio90/Dwarf#75]
Phone: Nexus 5X - Android 8.1.0
root: magisk (Magisk Hide -> OFF)
frida: last _(v12.8.20)_
Python: 3.8.1 _([Pyenv](https://github.com/pyenv/pyenv))_
In virtualenv installed last frida-tools and Dwarf _(git clone)_

_If execute `frida-ps -U` in terminal, there is a list of processes_
![Dwarf empty process list](https://i.imgur.com/NPVhBv4.png)

**Comment by 4val0v** [comment]
Exactly the same behavior on Ubuntu 18.04 and Windows 7 (Python 3.7)

But if you execute `dwarf.py` with arguments:
```--target android --device 01dee3aca0b101b2 --debug-script com.mytestapp```
Then everything works

**Comment by PinkiePieStyle** [comment]
ive seen this before

in magisk/superuser is shell access enabled?
is adb.py get_frida_version returning the version

**Comment by 4val0v** [comment]
**The problem is that the [list_packages](https://github.com/iGio90/Dwarf/blob/991dc34ba2fa4de8f90180c8da746d6ba93e7340/dwarf_debugger/lib/adb.py#L460) method not start**


Magisk: shell access - ENABLED
```shell
shell@shamu:/ $ su
root@shamu:/ # id
uid=0(root) gid=0(root) context=u:r:magisk:s0
root@shamu:/ # 
```

[adb.py line 432](https://github.com/iGio90/Dwarf/blob/2a0abe413476d1e7ee4b91b32b6eef9e9aefa1a1/dwarf_debugger/lib/adb.py#L432)
```python
                result = self._do_adb_command('shell frida-server --version')
                print("frida ver: " + result)  # Added output !
```
Output:
```
frida ver: 12.8.20
```

**Comment by PinkiePieStyle** [comment]
No list_packages is not used there

your problem is somewhere here
https://github.com/iGio90/Dwarf/blob/master/dwarf_debugger/ui/widgets/device_bar.py#L343
if check is ok bar becomes green and it sends deviceid to window
self.onDeviceUpdated.emit(frida_device.id)
then it updates the lists here
https://github.com/iGio90/Dwarf/blob/master/dwarf_debugger/ui/device_window.py#L145
https://github.com/iGio90/Dwarf/blob/master/dwarf_debugger/ui/widgets/process_list.py#L150

**Comment by 4val0v** [comment]
[device_bar.py#L343](https://github.com/iGio90/Dwarf/blob/master/dwarf_debugger/ui/widgets/device_bar.py#L343)
![device_bar](https://user-images.githubusercontent.com/11297476/80307168-1ac09f00-87d0-11ea-8662-5b15ddd2ebd0.png)

[device_bar.py#L394](https://github.com/iGio90/Dwarf/blob/master/dwarf_debugger/ui/widgets/device_bar.py#L394)
![image](https://user-images.githubusercontent.com/11297476/80307782-f5ce2b00-87d3-11ea-8e61-eebbe5012a48.png)
![image](https://user-images.githubusercontent.com/11297476/80307877-97557c80-87d4-11ea-8051-0460f5b5406f.png)

[dwarf.py#L266](https://github.com/iGio90/Dwarf/blob/master/dwarf_debugger/dwarf.py#L266)
```
sys.exit(qapp.exec_())
```

![image](https://user-images.githubusercontent.com/11297476/80307798-10a09f80-87d4-11ea-9601-57d7f6998b0c.png)

**Comment by 4val0v** [comment]
https://github.com/iGio90/Dwarf/blob/edf0b54d2b9088fbbcde6b23315a474d848193eb/dwarf_debugger/ui/widgets/device_bar.py#L354

![Screenshot 2020-04-26 at 15 49 06](https://user-images.githubusercontent.com/11297476/80308161-0089bf80-87d6-11ea-8b53-d67a648f9779.png)

https://github.com/iGio90/Dwarf/blob/edf0b54d2b9088fbbcde6b23315a474d848193eb/dwarf_debugger/lib/adb.py#L451

![image](https://user-images.githubusercontent.com/11297476/80308073-907b3980-87d5-11ea-8db7-aff0409a5392.png)

**Comment by PinkiePieStyle** [comment]
thx

https://github.com/iGio90/Dwarf/commit/d224dced82dfc421da4470f657924b622ef329bd

**Comment by 4val0v** [comment]
Cool !!!!
thx !
![image](https://user-images.githubusercontent.com/11297476/80308497-17c9ac80-87d8-11ea-8cd3-920525e3a39d.png)
