### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by 4val0v** [iGio90/Dwarf#76]
Add an event log to the code using the [logging](https://docs.python.org/3/howto/logging.html) module

And as an option, controlling through [arguments](https://github.com/iGio90/Dwarf/blob/991dc34ba2fa4de8f90180c8da746d6ba93e7340/dwarf_debugger/dwarf.py#L90) or [configuration file](https://docs.python.org/3/library/logging.config.html)

This greatly simplifies error handling :)

**Comment by PinkiePieStyle** [comment]
-ds gives some logging but thats all for 1.x
working on 2.0

**Comment by 4val0v** [comment]
> working on 2.0

2 version is not yet available ?
I would like to try working with version 2 

Ver 2 looks cool 👍 
https://www.youtube.com/watch?v=nvRvTU1IF_k&t=818s

**Comment by 4val0v** [comment]
@PinkiePieStyle `-ds` for frida scripts, but I would like [logging](https://github.com/iGio90/Dwarf/issues/76#issue-606903405) to be in python code methods

This would help to find such _([Issue 75](https://github.com/iGio90/Dwarf/issues/75#issuecomment-619545050))_ problems much faster.

**Comment by PinkiePieStyle** [comment]
yeah

but was my fault changed versionstuff  2days ago and not changed the other lines

https://github.com/iGio90/Dwarf/commit/4bed941d46db7d7c0a20b4e71325c4053b583138#diff-5d02f4f25e31c2ad38d801d38767122f
