### ISSUE TITLE
how to save java trace

### ISSUE THREAD

**Issue by magnobraw** [iGio90/Dwarf#83]
this program is amazing, how to save java trace log in file?

**Comment by PinkiePieStyle** [comment]
No support to save from ui, atm. Use startJavaTracer and give it some callback to log https://sec-r.et/dwarf/#startjavatracer
Or log to file on Device via Dwarfs FileSystem https://github.com/iGio90/DwarfCore/blob/master/src/fs.ts or Frida https://frida.re/docs/javascript-api/#file
