### ISSUE TITLE
There are too many same classes.

### ISSUE THREAD

**Issue by BurningTeng** [iGio90/Dwarf#86]
**Describe the bug**
There are too many same classes.

**To Reproduce**
1. Attach android app whose package is "com.example.myapplication"
2. Click on 'Java->Trace'
3. search "MainActivity"
4. See some same classes.

**Expected behavior**
For each, there should be only one class.

**Screenshots**
![burning](https://user-images.githubusercontent.com/20567891/99911217-ce215000-2d2d-11eb-86c5-1ae38f0c0cbf.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Smartphone (please complete the following information):**
 - OS: Android10

**Comment by PinkiePieStyle** [comment]
Ok seems @iGio90 changed the api to enumerate all loaders
https://github.com/iGio90/DwarfCore/commit/8f6035c9c891b2dae6c1196d6ec9de1e0c78e1fa#diff-769911c416ccf8514d8fd941ae0abe8fb5c606ade0c218e22151a5f5f9f3d700

ignore it or you can change it back to old func
from
https://github.com/iGio90/DwarfCore/blob/master/src/api.ts#L133
to
https://github.com/iGio90/DwarfCore/blob/0ee0a2c7234c0f5ec5ebcb10334b5c8bf4cb768e/src/api.ts#L120

it should work the same

but yeah it needs some fix showing the loader in ui too or whatever

**Comment by PinkiePieStyle** [comment]
Or replace in dwarf_debugger/lib/core.js
https://github.com/iGio90/Dwarf/blob/master/dwarf_debugger/lib/core.js#L1545
to 1563

with

```javascript
ldr.forEach(function (loaderz) {
    Java.classFactory.loader = loaderz;
    Java.enumerateLoadedClasses({
        onMatch: function onMatch(className) {
            if (logic_java_1.LogicJava !== null) {
                if (logic_java_1.LogicJava.javaClasses.indexOf(className) === -1) {
                    logic_java_1.LogicJava.javaClasses.push(className);
                }
            }

            //send("enumerate_java_classes_match:::" + className);
        },
        onComplete: function onComplete() {
            n++;

            if (n === ldr.length) {
                for (var i = 0; i < logic_java_1.LogicJava.javaClasses.length; i++) {
                    send("enumerate_java_classes_match:::" + logic_java_1.LogicJava.javaClasses[i]);
                }
                dwarf_1.Dwarf.loggedSend("enumerate_java_classes_complete:::");
            }
        },
    });
});
```

**Comment by BurningTeng** [comment]
I have tried the changed and it works fine. But it looks slower than before.
```
ldr.forEach(function (loaderz) {
    Java.classFactory.loader = loaderz;
    Java.enumerateLoadedClasses({
        onMatch: function onMatch(className) {
            if (logic_java_1.LogicJava !== null) {
                if (logic_java_1.LogicJava.javaClasses.indexOf(className) === -1) {
                    logic_java_1.LogicJava.javaClasses.push(className);
                }
            }

            //send("enumerate_java_classes_match:::" + className);
        },
        onComplete: function onComplete() {
            n++;

            if (n === ldr.length) {
                for (var i = 0; i < logic_java_1.LogicJava.javaClasses.length; i++) {
                    send("enumerate_java_classes_match:::" + logic_java_1.LogicJava.javaClasses[i]);
                }
                dwarf_1.Dwarf.loggedSend("enumerate_java_classes_complete:::");
            }
        },
    });
});
```
The result as below:
![burning](https://user-images.githubusercontent.com/20567891/99929805-88927080-2d89-11eb-9636-c4793debfef7.png)

**Comment by PinkiePieStyle** [comment]
yeah before it was caching and sending on match
now its caching and sending when enumeration is completed

is this filtered? here it shows a big list

**Comment by BurningTeng** [comment]
Yes. I use filter "MainActivy". Thanks for you explanation.

I have a question. 
If I want to hook onCreate of MyApplication, how to start dwarf?
```
public class MyApplication extends Application {

    private static String TAG = MyApplication.class.getSimpleName();

    @Override
    public void onCreate() {
        Log.d(TAG, "onCreate");
        super.onCreate();
    }

    @Override
    protected void attachBaseContext(Context base) {
        Log.d(TAG, "attachBaseContext");
        super.attachBaseContext(base);
    }
}

```

**Comment by PinkiePieStyle** [comment]
use -bs to break at start or tick the checkbox in ui dialog

**Comment by BurningTeng** [comment]
I use spawn way to suspend process. But how to resume the process.
![burning](https://user-images.githubusercontent.com/20567891/99970162-6ecb4a80-2dd6-11eb-849d-18fbb9bc2940.png)
Then the window is frozen. Later, there will be a dialog as below.

![burning](https://user-images.githubusercontent.com/20567891/99970335-a1754300-2dd6-11eb-871e-55641ff7d601.png)

**Comment by BurningTeng** [comment]
> use -bs to break at start or tick the checkbox in ui dialog

How to use "-bs" to break?
If the app is started, I can not hook onCreate of Application.
If the app is not started, I can not attach it.

**Comment by PinkiePieStyle** [comment]
application.oncreate gets hooked when u check the break at spawn checkbox and android is <= 6.0
on higher android it breaks at com.android.internal.os.RuntimeInit.commoninit
cant read the dialog but when it fails with 'cant spawn' bla its sometimes a timeout reboot device/restart frida can help

when it works the window where u select the app is closed and dwarf is halted at initbreakpoint
to resume use f5 or process->resume

**Comment by iGio90** [comment]
Has this been set? 

Do not remove the classloader enumeration thingy as many malware creates and uses custom class loaders, with the result that loaded classes wont be listed there.

**Comment by PinkiePieStyle** [comment]
not removed
