### ISSUE TITLE
Error message is shown when adding breakpoint for export function at first time

### ISSUE THREAD

**Issue by BurningTeng** [iGio90/Dwarf#88]
**Describe the bug**
Error message is shown when adding breakpoint of export function at first time.
Error message is below.

> TypeError: not a function at attach (/script1.js:3640) at putNativeBreakpoint (/script1.js:3872) at putBreakpoint (/script1.js:3854) at putBreakpoint (/script1.js:2126) at apply (native) at api (/script1.js:3508) at apply (native) at (frida/runtime/message-dispatcher.js:13) at c (frida/runtime/message-dispatcher.js:23)

**To Reproduce**
1. Attach android app whose package is "com.jingdong.app.mall"
2. Click on View->Panels->Modules
3. Add breakpoint for export function "Java_com_jingdong_common_utils_BitmapkitUtils_getSignFromJni" at first time
4. The error message is shown.
5.  Add breakpoint again, the console will print "0xc0b4a8b5 already has a breakpoint"
6. When I run app to trigger breakpoint, the breakpoint doesn't work. But following message will be shown:

> 19:32:31.758101  @thread 18321 loading class := com.tencent.smtt.net.AwNetworkUtils
19:32:34.505922  @thread 18048 loading class := com.jd.lib.search.view.Activity.SearchActivity
19:32:53.064365  @thread 18048 loading class := com.jd.lib.search.view.holder.tip.a
19:32:53.065138  @thread 18048 loading class := com.jd.lib.search.view.adapter.cw
19:32:53.068883  @thread 18048 loading class := com.jd.lib.search.view.holder.tip.b
19:32:53.072689  @thread 18048 loading class := com.jd.lib.search.view.adapter.cw$a
19:33:00.650688  @thread 18048 loading class := com.jd.lib.search.view.Activity.ProductListActivity

**Expected behavior**
No error message and breakpoint can work.

**Screenshots**
![burning](https://user-images.githubusercontent.com/20567891/99957661-07f06600-2dc3-11eb-8e60-cd4ae898cc80.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Smartphone (please complete the following information):**
 - OS: Android 10

**Comment by PinkiePieStyle** [comment]
try using it the frida way

```javascript
var expPtr=Module.findExportByName("libjdbitmapkit.so","Java_com_jingdong_common_utils_BitmapkitUtils_getSignFromJni");
console.log('ExportPtr: ' + expPtr);
Interceptor.attach(expPtr, {
    onEnter: function(args){
        console.log("onenter");
    },
    onLeave: function(retvalue){
        console.log("onleave");
    }
});
```

**Comment by BurningTeng** [comment]
I write code you mentioned above at Code Editor, but error message is shown. When I tried to trigger method Java_com_jingdong_common_utils_BitmapkitUtils_getSignFromJni, the code you mentioned is works.


Error message is :
TypeError: cannot read property 'then' of null at (frida/runtime/message-dispatcher.js:14) at c (frida/runtime/message-dispatcher.js:23)


![burning_first](https://user-images.githubusercontent.com/20567891/99968067-9d93f180-2dd3-11eb-8e2a-6a76769e3b78.png)

**Comment by feelworld** [comment]
i found the same question as you like this 
![Screenshot from 2020-11-25 16-43-21](https://user-images.githubusercontent.com/12098895/100203306-62adcd00-2f3d-11eb-8226-fbce6b0b76f8.png)
anybody  solve this

**Comment by feelworld** [comment]
my frida version is 14.0.8

**Comment by feelworld** [comment]
@PinkiePieStyle   are you there

**Comment by feelworld** [comment]
watchpoint has been solved  but  putbreakpoint problem still there   
![Screenshot from 2020-12-02 18-00-05](https://user-images.githubusercontent.com/12098895/100858430-ef6e0300-34c8-11eb-8d17-684ace1398d1.png)

**Comment by feelworld** [comment]
@PinkiePieStyle   are you there

**Comment by PinkiePieStyle** [comment]
yes looked into it and it needs some bigger change
switch to older frida version 12.xx
then in ~/.dwarf/preferences.json add
"disable_local_frida_update":true to prevent autoupdate
same on device remove frida 14.x and push some 12.xx

**Comment by feelworld** [comment]
> yes looked into it and it needs some bigger change
> switch to older frida version 12.xx
> then in ~/.dwarf/preferences.json add
> "disable_local_frida_update":true to prevent autoupdate
> same on device remove frida 14.x and push some 12.xx


I switch to older frida version 12.11.18 but when i attach process  

TypeError: undefined not callable (property 'find' of [object Array])
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:67616)
    at init (/script1.js:4177)

**Comment by feelworld** [comment]
my android version is 7.1.2

**Comment by PinkiePieStyle** [comment]
https://github.com/iGio90/Dwarf/commit/5df3a1e579a759e0f5106006c3454f67aa3d9d58#diff-5828cb1a613d58624de60b23bc27341e9c02b08a40182ecbda1c075f113742e1

restore the patched thing too

navigate to dwarf_debugger/lib/core.py

search for create_script
change this line back to 

self._script = self._process.create_script(script_content, runtime='v8')

**Comment by feelworld** [comment]
> [5df3a1e#diff-5828cb1a613d58624de60b23bc27341e9c02b08a40182ecbda1c075f113742e1](https://github.com/iGio90/Dwarf/commit/5df3a1e579a759e0f5106006c3454f67aa3d9d58#diff-5828cb1a613d58624de60b23bc27341e9c02b08a40182ecbda1c075f113742e1)
> 
> restore the patched thing too
> 
> navigate to dwarf_debugger/lib/core.py
> 
> search for create_script
> change this line back to
> 
> self._script = self._process.create_script(script_content, runtime='v8')

Thanks
