### ISSUE TITLE
Error message is shown when adding breakpoint 

### ISSUE THREAD

**Issue by feelworld** [iGio90/Dwarf#89]
![Screenshot from 2020-11-25 16-43-21](https://user-images.githubusercontent.com/12098895/100495601-f4107f80-3187-11eb-873d-46138b67b630.png)

iphone nexus5
android 5.0
frida-version  14.0.8

**Comment by PinkiePieStyle** [comment]
https://github.com/iGio90/Dwarf/commit/581e6400a1554fb978bbfbcc79604246c1ae6eb3
