### ISSUE TITLE
where is dwarf 2.0.0

### ISSUE THREAD

**Issue by feelworld** [iGio90/Dwarf#90]
i found lots of script which required Dwarf >= 2.0.0

**Comment by iGio90** [comment]
cc @PinkiePieStyle 

from what I know he was start a rework using electron rather then py but the covid thingy increased his working shifts (as many of us in the IT)

Im more involved with the core functionality so i cannot rly provide that much internals about the next release

**Comment by feelworld** [comment]
is there internal version which i can use?

**Comment by PinkiePieStyle** [comment]
What do you mean 'lots of scripts for >= 2.0' ?

There is only 
https://github.com/iGio90/NetworkRequests
https://github.com/PinkiePieStyle/dwarf_example_plugins

Sorry but internal == internal (Dwarf 2.x has less features atm)

With frida >14.x and the removed v8 engine it needs major changes in core of both dwarfs (dwarf+duk never worked)

**Comment by feelworld** [comment]
i  see

**Comment by feelworld** [comment]
where is  Range.py

**Comment by PinkiePieStyle** [comment]
?

**Comment by feelworld** [comment]
from dwarf_debugger.lib.types.range import Range

**Comment by feelworld** [comment]
range.py

**Comment by PinkiePieStyle** [comment]
No idea what you are doing :D
look in history for old files it was removed while ago (mid 2019 not sure)

**Comment by PinkiePieStyle** [comment]
https://github.com/iGio90/Dwarf/blob/04215c9f2edef720289ec7e3c54eb860399d0ed6/dwarf/lib/types/range.py

**Comment by feelworld** [comment]
it's missing range module when i use ucdwarf

**Comment by iGio90** [comment]
yes it makes sense... ucdwarf and r2dwarf plugins still need to be adapted to most recent version of dwarf. I didn't do it yet because we are planning that 2.0 since a lot. At the beginning we were supposed to drop 2.0 - 1 year ago but we meet many stucks, from pyqt to frida changing some stuff.

**Comment by PinkiePieStyle** [comment]
[Slack](https://join.slack.com/t/resecret/shared_invite/enQtMzc1NTg4MzE3NjA1LWZjY2YwMDA3OWZlZDg5Y2Y4NzRkYjE0ZjYzZGEwNDE2YmU0YTI0ZGJlZmNhODgzNDM1YzZmNWNlNGMwNDNhYTI)
