### ISSUE TITLE
the decompiler output is wrong

### ISSUE THREAD

**Issue by jambooid** [iGio90/Dwarf#91]
**Describe the bug**
the decompiler output is different with ida

**To Reproduce**
1. open an app with dwarf

**Expected behavior**
the decompiler should output the correct asm code
**Screenshots**
the wrong output
![image](https://user-images.githubusercontent.com/13990594/108594148-25799f80-73b3-11eb-8568-4672f4b1bcf2.png)
the correct output
![image](https://user-images.githubusercontent.com/13990594/108594175-54901100-73b3-11eb-9293-b141514cd269.png)

**Desktop (please complete the following information):**
 - OS: win10

**Smartphone (please complete the following information):**
 - Device: mi6x
 - OS:android 6.0

**Comment by iGio90** [comment]
Switch to arm thumb

**Comment by jambooid** [comment]
how to do that?

**Comment by iGio90** [comment]
If I'm not wrong @PinkiePieStyle added it to ctrl+t? I added it in the right click menu if I'm not wrong. Long time I don't meet arm32 binaries

**Comment by jambooid** [comment]
ctrl+ t is no availble.
no right menu is for switching to thumb.
![image](https://user-images.githubusercontent.com/13990594/108594296-2d860f00-73b4-11eb-8009-a9b262d3af99.png)

**Comment by jambooid** [comment]
![image](https://user-images.githubusercontent.com/13990594/108594320-560e0900-73b4-11eb-82a5-4c8bbe3ef36d.png)

**Comment by iGio90** [comment]
https://github.com/iGio90/Dwarf/blob/539e85c85b419590fd1397db0936159815974e11/dwarf_debugger/ui/widgets/disasm_view.py#L678

**Comment by iGio90** [comment]
Don't click on an asm line. Outside.  In the panel

**Comment by jambooid** [comment]
still don't find...
the dwarf version:
![image](https://user-images.githubusercontent.com/13990594/108595457-f2d3a500-73ba-11eb-9744-e829105cdf39.png)
right click: 
![image](https://user-images.githubusercontent.com/13990594/108595521-4a721080-73bb-11eb-98c6-f59b3289557a.png)
right click on the panel:
![image](https://user-images.githubusercontent.com/13990594/108595544-670e4880-73bb-11eb-9a06-fa91e07276d9.png)

**Comment by PinkiePieStyle** [comment]
Problem is in 
https://github.com/iGio90/Dwarf/blob/539e85c85b419590fd1397db0936159815974e11/dwarf_debugger/ui/widgets/disasm_view.py#L690

its doing only if nothing is in disasm

pretty sure its from old code

move the add_default_actions() there to line 697 with same indent from line below (698)
