### ISSUE TITLE
Step instruction doesn't work for Java in Android

### ISSUE THREAD

**Issue by mtsio** [iGio90/Dwarf#92]
**Describe the bug**
After hitting a breakpoint in a Java method for an attached application in Android I can't use the step functionality. Every time I press the step button I don't get any info and it seems to stuck. The same happens in debug builds. 
 
**To Reproduce**
1. Hit a breakpoint in a method
2. Click on Process->Step from the menu
3. See error in the console 

**Expected behavior**
The application should have executed the next instruction

**Desktop**
 - OS: [macOS]
 - Version [bigSur]

**Smartphone (please complete the following information):**
 - OS: [Android 9]

**Additional context**
I don't know if I'm missing something here. I noticed the following error in the console. I tried to modify the code a bit but with no luck.
Error:
payload: {'type': 'error', 'description': "TypeError: Cannot read property 'onInstruction' of null", 'stack': "TypeError: Cannot read property 'onInstruction' of null\n    at Function.putCalloutIfNeeded (/script1.js:5353:49)\n    at transform (/script1.js:5306:34)", 'fileName': '/script1.js', 'lineNumber': 5353, 'columnNumber': 49}

Thanks for releasing this!

**Comment by PinkiePieStyle** [comment]
Stepping is Native only
