### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by LanBaiCode** [iGio90/Dwarf#95]
I try to start the project but it crashes
![image](https://user-images.githubusercontent.com/72244576/162198487-9548ce8e-4b0f-4ebf-9e67-838295b5c4dd.png)
![image](https://user-images.githubusercontent.com/72244576/162198675-79f58bed-135c-40d5-881d-53898bb6ce34.png)
![image](https://user-images.githubusercontent.com/72244576/162198948-56065f47-f2b8-4384-8396-85be6b8991cf.png)

**Comment by LanBaiCode** [comment]
I updated the project but still can't open it
![image](https://user-images.githubusercontent.com/72244576/162348783-389983db-2290-46c0-8b09-67b7a0592b41.png)

**Comment by PinkiePieStyle** [comment]
Use master from git. Its not updated on pypi.
Its using your pypi version not the one in your Dwarf-master

`pip3 uninstall dwarf-debugger`

**Comment by LanBaiCode** [comment]
> 使用来自 git 的 master。它没有在pypi上更新。 它使用的是你的 pypi 版本，而不是你 Dwarf-master 中的那个
> 
> `pip3 uninstall dwarf-debugger`

![image](https://user-images.githubusercontent.com/72244576/162556883-b0b41541-9107-4e3e-ad9c-9af02e467981.png)

**Comment by LanBaiCode** [comment]
> pip3 uninstall dwarf-debugger

![image](https://user-images.githubusercontent.com/72244576/162601875-b91d8d28-3d26-4692-9d26-fa9eb1a36903.png)
It can be opened, but it will crash after clicking the apple icon
![image](https://user-images.githubusercontent.com/72244576/162601900-1653fea9-c596-4248-800b-e16c2bc93f40.png)

**Comment by LanBaiCode** [comment]
> > pip3 uninstall dwarf-debugger
> 
> ![image](https://user-images.githubusercontent.com/72244576/162601875-b91d8d28-3d26-4692-9d26-fa9eb1a36903.png) It can be opened, but it will crash after clicking the apple icon ![image](https://user-images.githubusercontent.com/72244576/162601900-1653fea9-c596-4248-800b-e16c2bc93f40.png)


![image](https://user-images.githubusercontent.com/72244576/162721459-2a308ac8-c8f5-4dde-b399-85213d1870be.png)
![image](https://user-images.githubusercontent.com/72244576/162725010-ce86e203-b60b-49bc-85c9-cd805e2c8b91.png)
![image](https://user-images.githubusercontent.com/72244576/162725213-6d9094b9-7a8c-48f2-8642-22828adeffb2.png)

**Comment by LanBaiCode** [comment]
![image](https://user-images.githubusercontent.com/72244576/162727260-cbddccc3-cd6a-4726-8d95-6a33e2c8b271.png)
Android

**Comment by LanBaiCode** [comment]
![image](https://user-images.githubusercontent.com/72244576/162865442-217e590d-b3f3-4a8c-94a8-fbed39112057.png)

**Comment by LanBaiCode** [comment]
![image](https://user-images.githubusercontent.com/72244576/162865496-13acf929-8b12-4fec-aa18-c6ec1267f38a.png)

**Comment by LanBaiCode** [comment]
![image](https://user-images.githubusercontent.com/72244576/162920573-a1405ae0-da10-4de4-a00a-9d57450ac017.png)
![image](https://user-images.githubusercontent.com/72244576/162921432-7406850d-9332-4bd9-aaec-de8f941b8656.png)

![image](https://user-images.githubusercontent.com/72244576/162921050-e9e891e1-80d7-436f-8ca8-5f44178d4fae.png)
![image](https://user-images.githubusercontent.com/72244576/162921297-65ac380c-3b13-4951-b33f-4f656681a536.png)

**Comment by PinkiePieStyle** [comment]
Ok think here it ends with fixing...
Your process is crashing/terminated so you have to figure out why. (adb logcat)
In the image with the "Breakpoint all methods" there are no methods listed and your process was terminated before. Thats why it shows the error, there is no frida/script attached anymore

**Comment by LanBaiCode** [comment]
> Yeah but there is nothing i can do atm. Its your target you have to figure out what it is doing...
> 
> In the moment you place the watchpoint dwarf is removing permissions from that memory location. And then handles "access-violation" in this handler it restores permissions and adds Breakpoint/Interceptor to break at address wich caused the exception.
> 
> You can simply recreate the behavior and use own exception handler `Memory.protect(memorylocation, 1, "---")`
> 
> `Process.setExceptionHandler(callback)` https://frida.re/docs/javascript-api/#process-setexceptionhandler
> 
> Gives you something like:
> 
> ```
> {"type":"access-violation","address": XXXXXXX,"memory":{"operation": ????? ,"address": XXXXXXX}
> ...
> ```
> 
> Then restore to old permissions `Memory.protect(memorylocation, 1, oldPermissions)`

It means that I can't set watchpoints and breakpoints as fast and sensitively as gdb, right?

**Comment by PinkiePieStyle** [comment]
Not sure what you mean "Fast and sensitively"...
Dwarf is not gdb... maybe you are using wrong tool...

Looking at your screenshots you are trying to hack some game (unity) in a "cheatengine way"... How about using Cheatengine?
Or changing your workflow and use the tools in a way you are able to achieve your goal

**Comment by LanBaiCode** [comment]
> Not sure what you mean "Fast and sensitively"... Dwarf is not gdb... maybe you are using wrong tool...
> 
> Looking at your screenshots you are trying to hack some game (unity) in a "cheatengine way"... How about using Cheatengine? Or changing your workflow and use the tools in a way you are able to achieve your goal

ok, i don't have any other questions for now
