### ISSUE TITLE
no output while javascript injecting

### ISSUE THREAD

**Issue by b1gcat** [iGio90/Dwarf#98]
**Describe the bug**
I spawn a apk successfully and inject javascript, but get nothing output.

Did I make a mistake?

<img width="804" alt="image" src="https://user-images.githubusercontent.com/15025254/165666254-cb79cbc5-09ec-4ce4-a965-cd38fa2a1d93.png">

**Comment by PinkiePieStyle** [comment]
`log("whatever")`
logs to the console in ui

`console.log("whatever")`
logs to the os console window

**Comment by b1gcat** [comment]
very nice project
